typography_spectrum: 0.28157548583112657
color:
  brandStrength: 0.7820516529027373
  lightness: 0.3209861346986145
  saturation: 0.5546372905373573
  rhythmicContrast: 0.003472560551017523
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.24395147082395852
name: Rocket Mission
navigation:
  - name: Nav
    url: rocketmission.com
    type: external
title: Rocket Mission
description: Modern furniture for the journey
